. "$PSScriptRoot\LoadConfig.ps1"
. "$PSScriptRoot\LoadProfile.ps1"

. "$PSScriptRoot\Invoke-ZabbixApi.ps1"
. "$PSScriptRoot\GetMapData.ps1"
. "$PSScriptRoot\GetMapElements.ps1"
. "$PSScriptRoot\Get-MapDimensions.ps1"
. "$PSScriptRoot\New-LayoutGrid.ps1"
. "$PSScriptRoot\Build-PreviewLayout.ps1"
. "$PSScriptRoot\Apply-MapLayout.ps1"
. "$PSScriptRoot\Get-HostGroups.ps1"
. "$PSScriptRoot\Get-GroupHosts.ps1"
. "$PSScriptRoot\Compare-MapGroup.ps1"
. "$PSScriptRoot\Add-GroupHostsToMap.ps1"

. "$PSScriptRoot\SortEngine.ps1"
. "$PSScriptRoot\LayoutEngine.ps1"
. "$PSScriptRoot\PreviewEngine.ps1"
. "$PSScriptRoot\MapEngine.ps1"
. "$PSScriptRoot\SelectFixedElements.ps1"

. "$PSScriptRoot\SaveProfile.ps1"
. "$PSScriptRoot\getMaps.ps1"
. "$PSScriptRoot\selectMap.ps1"
. "$PSScriptRoot\saveprofile.ps1"
. "$PSScriptRoot\newProfile.ps1"